apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret #name inside the secret file
              key: mongo-user  #name of the key

        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret #name inside the secret file
              key: mongo-password

        - name: ME_CONFIG_MONGODB_SERVER  #this one is for the server
          valueFrom:
            configMapKeyRef:
              name: mongo-config #name of the config file
              key: mongo-url


---
# services file

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp  #service is attached to the deployment 'webapp' (from above)
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081  #from the container port
      nodePort: 30100 # will allocate a port from a range (default: 30000-32767)
    

